### ISSUE TITLE
error when testing

### ISSUE THREAD

**Issue by cww97** [graspnet/graspnet-baseline#11]
```
$ bash command_test.sh
WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
Loading data path and collision labels...: 100%|█████████████████████████████████████████████████████████████████████████████| 90/90 [00:00<00:00, 328.38it/s]
23040
23040
-> loaded checkpoint logs/log_rs/checkpoint-rs.tar (epoch: 18)
Traceback (most recent call last):
  File "test.py", line 117, in <module>
    inference()
  File "test.py", line 71, in inference
    for batch_idx, batch_data in enumerate(TEST_DATALOADER):
  File "/home/ubuntu/miniconda/envs/grasp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/ubuntu/miniconda/envs/grasp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/miniconda/envs/grasp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/ubuntu/miniconda/envs/grasp/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/grasp/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/miniconda/envs/grasp/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/miniconda/envs/grasp/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/ssd/chenweiwen/baseline-graspnet/dataset/graspnet_dataset.py", line 102, in __getitem__
    return self.get_data(index)
  File "/mnt/ssd/chenweiwen/baseline-graspnet/dataset/graspnet_dataset.py", line 105, in get_data
    color = np.array(Image.open(self.colorpath[index]), dtype=np.float32) / 255.0
  File "/home/ubuntu/miniconda/envs/grasp/lib/python3.6/site-packages/PIL/Image.py", line 2904, in open
    fp = builtins.open(filename, "rb")
OSError: [Errno 40] Too many levels of symbolic links: '/data/Benchmark/graspnet/scenes/scene_0100/realsense/rgb/0000.png'
```

**Comment by Fang-Haoshu** [comment]
Hi, you might want to check the data since it is reported that:

OSError: [Errno 40] Too many levels of symbolic links:
